packages:
  - tools/*
  - packages/*
  - docs/*

catalog:
  '@ls-lint/ls-lint': ^2.3.1
  '@microsoft/api-extractor': ^7.56.0
  '@nx/devkit': 22.4.4
  '@nx/eslint-plugin': 22.4.4
  '@nx/jest': 22.4.4
  '@nx/js': 22.4.4
  '@nx/plugin': 22.4.4
  '@nx/workspace': 22.4.4
  '@storm-software/build-tools': ^0.158.81
  '@storm-software/config': ^1.135.1
  '@storm-software/config-tools': ^1.189.0
  '@storm-software/cspell': ^0.45.75
  '@storm-software/esbuild': ^0.53.81
  '@storm-software/eslint': ^0.169.83
  '@storm-software/git-tools': ^2.124.66
  '@storm-software/linting-tools': ^1.132.81
  '@storm-software/markdownlint': ^0.30.75
  '@storm-software/prettier': ^0.57.80
  '@storm-software/testing-tools': ^1.119.75
  '@storm-software/tsconfig': ^0.47.75
  '@storm-software/tsdoc': ^0.13.75
  '@storm-software/unbuild': ^0.57.81
  '@storm-software/untyped': ^0.24.62
  '@storm-software/workspace-tools': ^1.294.32
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.11
  '@swc/helpers': ^0.5.18
  '@swc/wasm': ^1.15.11
  '@taplo/cli': ^0.7.0
  '@types/jest': ^29.5.14
  '@types/node': ^22.19.7
  copyfiles: ^2.4.1
  defu: ^6.1.4
  esbuild: ^0.24.2
  eslint: ^9.39.2
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-environment-node: ^30.2.0
  jiti: ^2.6.1
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  nx: 22.3.1
  prettier: ^3.8.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-native: ^0.77.0
  rimraf: ^6.1.2
  sherif: ^1.10.0
  ts-jest: ^29.4.6
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: ^8.3.5
  typescript: 5.8.3
  unbuild: ^3.6.1
  verdaccio: 6.2.4
  zx: ^8.8.5

configDependencies:
  pnpm-plugin-storm-software: 0.1.4+sha512-Hegfb70ijqCc65CZwy8aLYhxrYQv3Wo+MZXqSfNAfcge7iSGYm2J3ydU5zkmf89JSvMOJy8J6lo/TMynBGvgtA==

fetchTimeout: 240000

minimumReleaseAgeExclude:
  - '@storm-software/*'
  - '@stryke/*'
  - '@powerlines/*'
  - powerlines

overrides:
  '@monorepo-template/tools-config': workspace:*
  '@monorepo-template/tools-scripts': workspace:*
  cookie: '>=0.7.0'
  debug: '>=4.4.0'
  follow-redirects: '>=1.15.9'
  got: '>=14.4.5'
  ip: '>=2.0.1'
  loader-utils: '>=3.3.1'
  markdown-it: '>=14.1.0'
  micromatch: '>=4.0.8'
  next: '>=13.4.20-canary.13'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  path-to-regexp: '>=0.1.12'
  postcss: '>=8.5.1'
  shell-quote: '>=1.8.2'
  simple-git: '>=3.27.0'
  zod: '>=4.0.5'

shamefullyHoist: true

useNodeVersion: 24.11.1
