packages:
  - tools/*
  - packages/*
  - docs/*

catalog:
  '@ls-lint/ls-lint': ^2.3.1
  '@microsoft/api-extractor': ^7.49.2
  '@nx/devkit': 22.3.1
  '@nx/eslint-plugin': 22.3.1
  '@nx/jest': 22.3.1
  '@nx/js': 22.3.1
  '@nx/plugin': 22.3.1
  '@nx/workspace': 22.3.1
  '@storm-software/build-tools': ^0.158.71
  '@storm-software/config': ^1.134.71
  '@storm-software/config-tools': ^1.188.71
  '@storm-software/cspell': ^0.45.70
  '@storm-software/esbuild': ^0.53.71
  '@storm-software/eslint': ^0.169.72
  '@storm-software/git-tools': ^2.124.54
  '@storm-software/linting-tools': ^1.132.71
  '@storm-software/markdownlint': ^0.30.70
  '@storm-software/prettier': ^0.57.70
  '@storm-software/testing-tools': ^1.119.70
  '@storm-software/tsconfig': ^0.47.70
  '@storm-software/tsdoc': ^0.13.70
  '@storm-software/unbuild': ^0.57.71
  '@storm-software/untyped': ^0.24.52
  '@storm-software/workspace-tools': ^1.294.17
  '@swc-node/register': ^1.10.10
  '@swc/core': ^1.11.22
  '@swc/helpers': ^0.5.17
  '@swc/wasm': ^1.11.24
  '@taplo/cli': ^0.7.0
  '@types/jest': ^29.5.14
  '@types/node': ^22.19.3
  copyfiles: ^2.4.1
  defu: ^6.1.4
  esbuild: ^0.24.2
  eslint: ^9.39.2
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-environment-node: ^30.2.0
  jiti: ^2.4.2
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  nx: 22.3.1
  prettier: ^3.7.4
  react: ^19.0.0
  react-dom: ^19.0.0
  react-native: ^0.77.0
  rimraf: ^6.1.2
  sherif: ^1.0.0
  ts-jest: ^29.4.6
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: ^8.3.5
  typescript: 5.8.3
  unbuild: ^3.3.1
  verdaccio: 6.0.5
  zx: ^8.8.5

configDependencies:
  pnpm-plugin-storm-software: 0.1.4+sha512-Hegfb70ijqCc65CZwy8aLYhxrYQv3Wo+MZXqSfNAfcge7iSGYm2J3ydU5zkmf89JSvMOJy8J6lo/TMynBGvgtA==

fetchTimeout: 240000

minimumReleaseAgeExclude:
  - '@storm-software/*'
  - '@stryke/*'
  - '@powerlines/*'
  - powerlines

overrides:
  '@monorepo-template/tools-config': workspace:*
  '@monorepo-template/tools-scripts': workspace:*
  cookie: '>=0.7.0'
  debug: '>=4.4.0'
  follow-redirects: '>=1.15.9'
  got: '>=14.4.5'
  ip: '>=2.0.1'
  loader-utils: '>=3.3.1'
  markdown-it: '>=14.1.0'
  micromatch: '>=4.0.8'
  next: '>=13.4.20-canary.13'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  path-to-regexp: '>=0.1.12'
  postcss: '>=8.5.1'
  shell-quote: '>=1.8.2'
  simple-git: '>=3.27.0'
  zod: '>=4.0.5'

shamefullyHoist: true

useNodeVersion: 24.11.1
